spring.application.name:cheqr

#secret key for encryption
cheqr.app.encryption_secret_key:CFRk2rLqQI2TEn03vTnLwV8dqj0WN0dkwx7zLs/gzHw=

cheqr.app.jwtExpirationMs:86400000

logging.level.ROOT: INFO
logging.level.ROOT.org.hibernate.SQL: INFO
logging.level.ROOT.org.springframework: INFO

spring.datasource.url: jdbc:postgresql://localhost:5432/cheqr_db
spring.datasource.username: postgres
spring.datasource.password: postgresADMIN
#spring.jpa.hibernate.ddl-auto=update


spring.jpa.open-in-view: false
#spring.jpa.hibernate.ddl-auto: validate
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.default_schema: cheqr_schema

logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

management.endpoints.web.exposure.include=*
#spring.jackson.stream-write-constraints.max-nesting-depth=2000

server.max-http-request-header-size=64KB

#To generate the keystore key for making requests to be https
#Run the following command in any terminal
#keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -validity 3650
#move the keystore.p12 file from the location where it was generated to the project_directory/resources folder

#Keystore details
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=keystore2301password
#server.ssl.key-alias=tomcat
#Standard HTTPS port is 443, but 8443 is commonly used for development
#server.port=8443 


server.port:8080
server.address:0.0.0.0